#!/usr/bin/env node

let data = {
    name: "guerre_rep",
    layout: "guerre",
    data: {
        tematiche: [
            { name: "repubblica", foto: ["repubblica_2.jpg", "repubblica_3.jpg"], didascalie: ["Ascari bla bla", "Aaascari 2"], },
            { name: "garibaldi", foto: ["garibaldi_2.jpg", "garibaldi_3.jpg"], didascalie: ["Ascari bla bla", "Aaascari 2"], },
        ]
    }
}

console.log(JSON.stringify(data, undefined, 4));
