#!/usr/bin/env ruby

require 'json'
require 'open-uri'

data = {
    "name" => "totem_1",
    "layout" => "totem",
}

open('http://192.168.0.124/swi/service/rest/v1/app-totem') { |content| data["data"] = JSON.parse(content.read) }

puts JSON.pretty_generate(data)
